// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Analizadores/lex.jflex

package Analizadores;
import java_cup.runtime.*;
import Errores.*;
import Instrucciones.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\0"+
    "\1\4\1\0\1\5\2\0\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\2\22\1\23\1\24\2\25\1\26\1\0\1\27\2\0"+
    "\1\30\1\31\1\0\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\2\44\1\60\1\44\1\61\1\0\1\62\1\0"+
    "\1\63\1\0\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\2\44\1\60\1\44\1\64\1\0\1\65\7\0\1\3"+
    "\71\0\1\66\160\0\2\67\115\0\1\70\u01a8\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\20\15\1\16"+
    "\1\17\1\20\1\21\2\1\2\0\1\22\2\0\1\23"+
    "\27\0\1\24\5\0\1\25\2\0\1\22\2\0\1\26"+
    "\1\0\1\27\1\12\1\30\12\0\1\31\12\0\1\32"+
    "\1\33\10\0\1\34\4\0\1\27\3\0\1\35\23\0"+
    "\1\36\1\37\22\0\1\40\5\0\1\41\1\42\3\0"+
    "\1\43\1\44\6\0\1\45\2\0\1\46\16\0\1\47"+
    "\4\0\1\50\2\0\1\51\1\0\1\52\4\0\1\53"+
    "\16\0\1\54\7\0\1\55\2\0\1\56\4\0\1\57"+
    "\1\60\1\0\1\61\3\0\1\62\2\0\1\63\1\64"+
    "\2\0\1\65\1\66\1\67\2\0\1\70\5\0\1\71"+
    "\1\72\10\0\1\73\10\0\1\74\1\0\1\75\5\0"+
    "\1\76\1\77\5\0\1\100\1\101\1\0\1\102\1\0"+
    "\1\103\1\104";

  private static int [] zzUnpackAction() {
    int [] result = new int[312];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\71\0\162\0\253\0\71\0\71\0\71"+
    "\0\71\0\71\0\344\0\u011d\0\u0156\0\71\0\71\0\u018f"+
    "\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\71\0\u02e5\0\u031e"+
    "\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\71"+
    "\0\71\0\u04e6\0\71\0\u031e\0\u0474\0\162\0\u051f\0\u0558"+
    "\0\u0591\0\u05ca\0\71\0\u0603\0\u063c\0\u0675\0\u06ae\0\u06e7"+
    "\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804\0\u083d\0\u0876\0\u08af"+
    "\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05\0\u0a3e\0\u0a77"+
    "\0\u0ab0\0\u0ae9\0\71\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06"+
    "\0\71\0\u0c3f\0\u0c78\0\71\0\u0558\0\u0cb1\0\71\0\u0cea"+
    "\0\u063c\0\u0675\0\71\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07"+
    "\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf"+
    "\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197"+
    "\0\71\0\71\0\u11d0\0\u1209\0\u1242\0\u127b\0\u12b4\0\u12ed"+
    "\0\u1326\0\u135f\0\u0c78\0\u1398\0\u13d1\0\u140a\0\u1443\0\71"+
    "\0\u147c\0\u14b5\0\u14ee\0\71\0\u1527\0\u1560\0\u1599\0\u15d2"+
    "\0\u160b\0\u1644\0\u167d\0\u16b6\0\u16ef\0\u1728\0\u1761\0\u179a"+
    "\0\u17d3\0\u180c\0\u1845\0\u187e\0\u18b7\0\u18f0\0\u1929\0\71"+
    "\0\71\0\u1962\0\u199b\0\u19d4\0\u1a0d\0\u1a46\0\u1a7f\0\u1ab8"+
    "\0\u1af1\0\u1b2a\0\u1b63\0\u1b9c\0\u1bd5\0\u1c0e\0\u1c47\0\u1c80"+
    "\0\u1cb9\0\u1cf2\0\u1d2b\0\71\0\u1d64\0\u1d9d\0\u1dd6\0\u1e0f"+
    "\0\u1e48\0\71\0\u1e81\0\u1eba\0\u1ef3\0\u1f2c\0\u1f65\0\u1f9e"+
    "\0\u1fd7\0\u2010\0\u2049\0\u2082\0\u20bb\0\u20f4\0\71\0\u212d"+
    "\0\u2166\0\71\0\u219f\0\u21d8\0\u2211\0\u224a\0\u2283\0\u22bc"+
    "\0\u22f5\0\u232e\0\u2367\0\u23a0\0\u23d9\0\u2412\0\u244b\0\u2484"+
    "\0\71\0\u24bd\0\u24f6\0\u252f\0\u2568\0\71\0\u25a1\0\u25da"+
    "\0\71\0\u2613\0\71\0\u264c\0\u2685\0\u26be\0\u26f7\0\71"+
    "\0\u2730\0\u2769\0\u27a2\0\u27db\0\u2814\0\u284d\0\u2886\0\u28bf"+
    "\0\u28f8\0\u2931\0\u296a\0\u29a3\0\u29dc\0\u2a15\0\71\0\u2a4e"+
    "\0\u2a87\0\u2ac0\0\u2af9\0\u2b32\0\u2b6b\0\u2ba4\0\71\0\u2bdd"+
    "\0\u2c16\0\71\0\u2c4f\0\u2c88\0\u2cc1\0\u2cfa\0\71\0\71"+
    "\0\u2d33\0\71\0\u2d6c\0\u2da5\0\u2dde\0\71\0\u2e17\0\u2e50"+
    "\0\u2e89\0\71\0\u2ec2\0\u2efb\0\71\0\71\0\71\0\u2f34"+
    "\0\u2f6d\0\71\0\u2fa6\0\u2fdf\0\u3018\0\u3051\0\u308a\0\71"+
    "\0\71\0\u30c3\0\u30fc\0\u3135\0\u316e\0\u31a7\0\u31e0\0\u3219"+
    "\0\u3252\0\71\0\u328b\0\u32c4\0\u32fd\0\u3336\0\u336f\0\u33a8"+
    "\0\u33e1\0\u341a\0\71\0\u3453\0\71\0\u348c\0\u34c5\0\u34fe"+
    "\0\u3537\0\u3570\0\71\0\71\0\u35a9\0\u35e2\0\u361b\0\u3654"+
    "\0\u368d\0\71\0\71\0\u36c6\0\71\0\u36ff\0\71\0\71";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[312];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\2\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\2\1\14\10\15\1\16"+
    "\1\2\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\3\26\1\31\1\32\1\33\1\34"+
    "\1\26\1\35\1\36\2\26\1\37\1\26\1\40\1\41"+
    "\1\42\2\2\1\43\1\44\1\45\71\0\2\46\2\47"+
    "\1\50\64\46\5\0\1\51\24\0\27\52\40\0\1\53"+
    "\51\0\1\54\4\0\1\55\67\0\1\56\1\0\10\15"+
    "\111\0\1\57\71\0\1\60\52\0\1\61\15\0\1\62"+
    "\56\0\1\63\75\0\1\64\3\0\1\65\4\0\1\66"+
    "\13\0\1\66\32\0\1\67\7\0\1\70\13\0\1\71"+
    "\10\0\1\70\33\0\1\72\104\0\1\73\1\74\53\0"+
    "\1\75\3\0\1\76\3\0\1\77\5\0\1\100\16\0"+
    "\1\77\51\0\1\101\5\0\1\102\65\0\1\103\7\0"+
    "\1\104\37\0\1\105\15\0\1\106\56\0\1\107\70\0"+
    "\1\110\3\0\1\111\24\0\1\111\37\0\1\112\64\0"+
    "\27\113\10\0\4\47\1\114\64\47\2\115\2\0\1\50"+
    "\64\115\64\0\1\116\12\0\1\117\62\0\11\54\1\120"+
    "\57\54\2\121\2\0\65\121\17\0\10\122\77\0\1\123"+
    "\103\0\1\124\55\0\1\125\15\0\1\126\63\0\1\127"+
    "\1\130\104\0\1\131\43\0\1\132\107\0\1\133\76\0"+
    "\1\134\52\0\1\135\72\0\1\136\70\0\1\137\55\0"+
    "\1\140\17\0\1\141\13\0\1\141\51\0\1\142\57\0"+
    "\1\143\1\0\1\144\24\0\1\144\61\0\1\145\57\0"+
    "\1\146\5\0\1\147\51\0\1\150\67\0\1\151\110\0"+
    "\1\152\61\0\1\153\76\0\1\154\13\0\1\154\53\0"+
    "\1\155\72\0\1\156\64\0\1\157\3\0\1\160\53\0"+
    "\1\161\103\0\1\162\34\0\10\113\3\0\27\113\2\0"+
    "\1\163\25\0\1\164\3\0\1\165\1\166\1\167\42\0"+
    "\11\54\1\120\4\54\1\170\52\54\45\0\1\171\61\0"+
    "\1\172\64\0\1\173\106\0\1\174\103\0\1\175\52\0"+
    "\1\176\57\0\1\177\104\0\1\200\55\0\1\201\4\0"+
    "\1\202\24\0\1\202\55\0\1\203\13\0\1\203\63\0"+
    "\1\204\41\0\1\205\72\0\1\206\107\0\1\207\66\0"+
    "\1\210\70\0\1\211\51\0\1\212\104\0\1\213\70\0"+
    "\1\214\70\0\1\215\67\0\1\216\57\0\1\217\74\0"+
    "\1\220\24\0\1\220\33\0\1\221\74\0\1\222\70\0"+
    "\1\223\102\0\1\224\76\0\1\225\47\0\1\226\52\0"+
    "\2\166\1\227\72\0\4\230\61\0\10\230\61\0\1\230"+
    "\5\0\2\230\100\0\1\231\101\0\1\232\55\0\1\233"+
    "\76\0\1\234\6\0\1\235\5\0\1\236\7\0\1\234"+
    "\51\0\1\237\76\0\1\240\61\0\1\241\63\0\1\242"+
    "\24\0\1\242\41\0\1\243\100\0\1\244\57\0\1\245"+
    "\6\0\1\246\2\0\1\247\2\0\1\250\13\0\1\250"+
    "\42\0\1\251\24\0\1\251\54\0\1\252\47\0\1\253"+
    "\100\0\1\254\24\0\1\254\37\0\1\255\74\0\1\256"+
    "\24\0\1\256\54\0\1\257\70\0\1\260\52\0\1\261"+
    "\110\0\1\262\66\0\1\263\64\0\1\264\76\0\1\265"+
    "\66\0\1\266\64\0\1\267\53\0\1\270\55\0\3\230"+
    "\134\0\1\52\35\0\1\271\70\0\1\272\113\0\1\273"+
    "\62\0\1\274\53\0\1\275\70\0\1\276\121\0\1\277"+
    "\62\0\1\300\47\0\1\301\73\0\1\302\107\0\1\303"+
    "\70\0\1\304\50\0\1\305\3\0\1\306\24\0\1\306"+
    "\33\0\1\307\74\0\1\310\3\0\1\311\24\0\1\311"+
    "\51\0\1\312\103\0\1\313\53\0\1\314\76\0\1\315"+
    "\13\0\1\315\50\0\1\316\103\0\1\317\70\0\1\320"+
    "\55\0\1\321\73\0\1\322\65\0\1\323\54\0\1\324"+
    "\76\0\1\325\24\0\1\325\50\0\1\326\56\0\1\327"+
    "\102\0\1\330\57\0\1\331\66\0\1\332\107\0\1\333"+
    "\62\0\1\334\57\0\1\335\66\0\1\336\74\0\1\337"+
    "\70\0\1\340\64\0\1\341\105\0\1\342\76\0\1\343"+
    "\51\0\1\344\105\0\1\345\55\0\1\346\77\0\1\347"+
    "\73\0\1\350\60\0\1\351\24\0\1\351\33\0\1\352"+
    "\106\0\1\353\70\0\1\354\52\0\1\355\100\0\1\356"+
    "\24\0\1\356\54\0\1\357\47\0\1\360\74\0\1\361"+
    "\105\0\1\362\70\0\1\363\47\0\1\364\106\0\1\365"+
    "\70\0\1\366\73\0\1\367\71\0\1\370\13\0\1\370"+
    "\53\0\1\371\62\0\1\372\57\0\1\373\104\0\1\374"+
    "\67\0\1\375\53\0\1\376\114\0\1\377\70\0\1\u0100"+
    "\65\0\1\u0101\70\0\1\u0102\100\0\1\u0103\70\0\1\u0104"+
    "\61\0\1\u0105\13\0\1\u0105\32\0\1\u0106\111\0\1\u0107"+
    "\70\0\1\203\53\0\1\u0108\100\0\1\u0109\75\0\1\u010a"+
    "\64\0\1\u010b\57\0\1\u010c\74\0\1\u010d\24\0\1\u010d"+
    "\36\0\1\u010e\110\0\1\u010f\62\0\1\u0110\57\0\1\u0111"+
    "\115\0\1\u0112\47\0\1\u0113\24\0\1\u0113\43\0\1\u0114"+
    "\24\0\1\u0114\47\0\1\u0115\60\0\1\u0116\107\0\1\u0117"+
    "\62\0\1\u0118\71\0\1\u0119\70\0\1\u011a\73\0\1\u011b"+
    "\64\0\1\u011c\61\0\1\u011d\70\0\1\u011e\66\0\1\u011f"+
    "\107\0\1\u0120\66\0\1\u0121\72\0\1\u0122\62\0\1\u0123"+
    "\53\0\1\u0124\103\0\1\u0125\101\0\1\u0126\70\0\1\u0127"+
    "\61\0\1\u0128\74\0\1\u0129\47\0\1\u012a\74\0\1\u012b"+
    "\106\0\1\u012c\13\0\1\u012c\32\0\1\u012d\70\0\1\u012e"+
    "\113\0\1\u012f\63\0\1\u0130\73\0\1\u0131\62\0\1\u0132"+
    "\70\0\1\u0133\55\0\1\u0134\112\0\1\u0135\13\0\1\u0135"+
    "\42\0\1\u0136\24\0\1\u0136\46\0\1\u0137\73\0\1\u0138"+
    "\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14136];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\5\11\3\1\2\11\6\1\1\11"+
    "\11\1\2\11\1\1\1\11\2\1\2\0\1\1\2\0"+
    "\1\11\27\0\1\11\5\0\1\11\2\0\1\11\2\0"+
    "\1\11\1\0\2\1\1\11\12\0\1\1\12\0\2\11"+
    "\10\0\1\1\4\0\1\11\3\0\1\11\23\0\2\11"+
    "\22\0\1\11\5\0\1\11\1\1\3\0\2\1\6\0"+
    "\1\11\2\0\1\11\16\0\1\11\4\0\1\11\2\0"+
    "\1\11\1\0\1\11\4\0\1\11\16\0\1\11\7\0"+
    "\1\11\2\0\1\11\4\0\2\11\1\0\1\11\3\0"+
    "\1\11\2\0\1\1\1\11\2\0\3\11\2\0\1\11"+
    "\5\0\2\11\10\0\1\11\10\0\1\11\1\0\1\11"+
    "\5\0\2\11\5\0\2\11\1\0\1\11\1\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[312];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { //System.out.println("Error Lexico: " + yytext() + " Linea " + (yyline + 1) + " Columna " + (yycolumn + 1));
        Instruction.list.addError(new Error_("Token no valido: " + yytext(), "Lexico", yyline + 1, yycolumn + 1));
            }
            // fall through
          case 69: break;
          case 2:
            { /* Espacios en blanco se ignoran */
            }
            // fall through
          case 70: break;
          case 3:
            { return new Symbol(Simbolos.tparA, yycolumn, yyline, yytext());
            }
            // fall through
          case 71: break;
          case 4:
            { return new Symbol(Simbolos.tparC, yycolumn, yyline, yytext());
            }
            // fall through
          case 72: break;
          case 5:
            { return new Symbol(Simbolos.tmul, yycolumn, yyline, yytext());
            }
            // fall through
          case 73: break;
          case 6:
            { return new Symbol(Simbolos.tsum, yycolumn, yyline, yytext());
            }
            // fall through
          case 74: break;
          case 7:
            { return new Symbol(Simbolos.tcoma, yycolumn, yyline, yytext());
            }
            // fall through
          case 75: break;
          case 8:
            { return new Symbol(Simbolos.trest, yycolumn, yyline, yytext());
            }
            // fall through
          case 76: break;
          case 9:
            { return new Symbol(Simbolos.tdiv, yycolumn, yyline, yytext());
            }
            // fall through
          case 77: break;
          case 10:
            { return new Symbol(Simbolos.tnum, yycolumn, yyline, yytext());
            }
            // fall through
          case 78: break;
          case 11:
            { return new Symbol(Simbolos.tpcoma, yycolumn, yyline, yytext());
            }
            // fall through
          case 79: break;
          case 12:
            { return new Symbol(Simbolos.tQn_C, yycolumn, yyline, yytext());
            }
            // fall through
          case 80: break;
          case 13:
            { return new Symbol(Simbolos.tletras, yycolumn, yyline, yytext());
            }
            // fall through
          case 81: break;
          case 14:
            { return new Symbol(Simbolos.tcorA, yycolumn, yyline, yytext());
            }
            // fall through
          case 82: break;
          case 15:
            { return new Symbol(Simbolos.tcorC, yycolumn, yyline, yytext());
            }
            // fall through
          case 83: break;
          case 16:
            { return new Symbol(Simbolos.tunder, yycolumn, yyline, yytext());
            }
            // fall through
          case 84: break;
          case 17:
            { return new Symbol(Simbolos.tQn_A, yycolumn, yyline, yytext());
            }
            // fall through
          case 85: break;
          case 18:
            { return new Symbol(Simbolos.tcadena, yycolumn, yyline, yytext());
            }
            // fall through
          case 86: break;
          case 19:
            { return new Symbol(Simbolos.tarrow, yycolumn, yyline, yytext());
            }
            // fall through
          case 87: break;
          case 20:
            { return new Symbol(Simbolos.tor, yycolumn, yyline, yytext());
            }
            // fall through
          case 88: break;
          case 21:
            { return new Symbol(Simbolos.tif, yycolumn, yyline, yytext());
            }
            // fall through
          case 89: break;
          case 22:
            { return new Symbol(Simbolos.tcaracter, yycolumn, yyline, yytext());
            }
            // fall through
          case 90: break;
          case 23:
            { /* Espacios en blanco, se ignoran */
            }
            // fall through
          case 91: break;
          case 24:
            { return new Symbol(Simbolos.tand, yycolumn, yyline, yytext());
            }
            // fall through
          case 92: break;
          case 25:
            { return new Symbol(Simbolos.tfin, yycolumn, yyline, yytext());
            }
            // fall through
          case 93: break;
          case 26:
            { return new Symbol(Simbolos.tmod, yycolumn, yyline, yytext());
            }
            // fall through
          case 94: break;
          case 27:
            { return new Symbol(Simbolos.tnot, yycolumn, yyline, yytext());
            }
            // fall through
          case 95: break;
          case 28:
            { return new Symbol(Simbolos.tvar_name, yycolumn, yyline, yytext());
            }
            // fall through
          case 96: break;
          case 29:
            { return new Symbol(Simbolos.tcomo, yycolumn, yyline, yytext());
            }
            // fall through
          case 97: break;
          case 30:
            { return new Symbol(Simbolos.telseif, yycolumn, yyline, yytext());
            }
            // fall through
          case 98: break;
          case 31:
            { return new Symbol(Simbolos.tfor, yycolumn, yyline, yytext());
            }
            // fall through
          case 99: break;
          case 32:
            { return new Symbol(Simbolos.tboolean, yycolumn, yyline, yytext());
            }
            // fall through
          case 100: break;
          case 33:
            { return new Symbol(Simbolos.tdo, yycolumn, yyline, yytext());
            }
            // fall through
          case 101: break;
          case 34:
            { return new Symbol(Simbolos.thasta, yycolumn, yyline, yytext());
            }
            // fall through
          case 102: break;
          case 35:
            { return new Symbol(Simbolos.tmayor, yycolumn, yyline, yytext());
            }
            // fall through
          case 103: break;
          case 36:
            { return new Symbol(Simbolos.tmenor, yycolumn, yyline, yytext());
            }
            // fall through
          case 104: break;
          case 37:
            { return new Symbol(Simbolos.tsegun, yycolumn, yyline, yytext());
            }
            // fall through
          case 105: break;
          case 38:
            { return new Symbol(Simbolos.tstring, yycolumn, yyline, yytext());
            }
            // fall through
          case 106: break;
          case 39:
            { return new Symbol(Simbolos.tendif, yycolumn, yyline, yytext());
            }
            // fall through
          case 107: break;
          case 40:
            { return new Symbol(Simbolos.tinicio, yycolumn, yyline, yytext());
            }
            // fall through
          case 108: break;
          case 41:
            { return new Symbol(Simbolos.tmetodo, yycolumn, yyline, yytext());
            }
            // fall through
          case 109: break;
          case 42:
            { return new Symbol(Simbolos.tint, yycolumn, yyline, yytext());
            }
            // fall through
          case 110: break;
          case 43:
            { return new Symbol(Simbolos.tbool, yycolumn, yyline, yytext());
            }
            // fall through
          case 111: break;
          case 44:
            { return new Symbol(Simbolos.tfuncion, yycolumn, yyline, yytext());
            }
            // fall through
          case 112: break;
          case 45:
            { return new Symbol(Simbolos.trepeat, yycolumn, yyline, yytext());
            }
            // fall through
          case 113: break;
          case 46:
            { return new Symbol(Simbolos.tchar, yycolumn, yyline, yytext());
            }
            // fall through
          case 114: break;
          case 47:
            { return new Symbol(Simbolos.texec, yycolumn, yyline, yytext());
            }
            // fall through
          case 115: break;
          case 48:
            { return new Symbol(Simbolos.tthen, yycolumn, yyline, yytext());
            }
            // fall through
          case 116: break;
          case 49:
            { return new Symbol(Simbolos.tes_igual, yycolumn, yyline, yytext());
            }
            // fall through
          case 117: break;
          case 50:
            { return new Symbol(Simbolos.tfin_for, yycolumn, yyline, yytext());
            }
            // fall through
          case 118: break;
          case 51:
            { return new Symbol(Simbolos.tprint, yycolumn, yyline, yytext());
            }
            // fall through
          case 119: break;
          case 52:
            { return new Symbol(Simbolos.tingresar, yycolumn, yyline, yytext());
            }
            // fall through
          case 120: break;
          case 53:
            { return new Symbol(Simbolos.twhile, yycolumn, yyline, yytext());
            }
            // fall through
          case 121: break;
          case 54:
            { return new Symbol(Simbolos.tpot, yycolumn, yyline, yytext());
            }
            // fall through
          case 122: break;
          case 55:
            { return new Symbol(Simbolos.treturn, yycolumn, yyline, yytext());
            }
            // fall through
          case 123: break;
          case 56:
            { return new Symbol(Simbolos.tcon_val, yycolumn, yyline, yytext());
            }
            // fall through
          case 124: break;
          case 57:
            { return new Symbol(Simbolos.tfin_segun, yycolumn, yyline, yytext());
            }
            // fall through
          case 125: break;
          case 58:
            { return new Symbol(Simbolos.tuntil, yycolumn, yyline, yytext());
            }
            // fall through
          case 126: break;
          case 59:
            { return new Symbol(Simbolos.tfin_metodo, yycolumn, yyline, yytext());
            }
            // fall through
          case 127: break;
          case 60:
            { return new Symbol(Simbolos.tfin_funcion, yycolumn, yyline, yytext());
            }
            // fall through
          case 128: break;
          case 61:
            { return new Symbol(Simbolos.tprintln, yycolumn, yyline, yytext());
            }
            // fall through
          case 129: break;
          case 62:
            { return new Symbol(Simbolos.tdifer, yycolumn, yyline, yytext());
            }
            // fall through
          case 130: break;
          case 63:
            { return new Symbol(Simbolos.tend_while, yycolumn, yyline, yytext());
            }
            // fall through
          case 131: break;
          case 64:
            { return new Symbol(Simbolos.tmayor_igual, yycolumn, yyline, yytext());
            }
            // fall through
          case 132: break;
          case 65:
            { return new Symbol(Simbolos.tmenor_igual, yycolumn, yyline, yytext());
            }
            // fall through
          case 133: break;
          case 66:
            { return new Symbol(Simbolos.tparams, yycolumn, yyline, yytext());
            }
            // fall through
          case 134: break;
          case 67:
            { return new Symbol(Simbolos.tincrease, yycolumn, yyline, yytext());
            }
            // fall through
          case 135: break;
          case 68:
            { return new Symbol(Simbolos.telse, yycolumn, yyline, yytext());
            }
            // fall through
          case 136: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
