
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tmul = 6;
  public static final int trest = 3;
  public static final int tbool = 12;
  public static final int tnum = 2;
  public static final int tcadena = 11;
  public static final int tsum = 4;
  public static final int tinicio = 9;
  public static final int tpot = 7;
  public static final int tmod = 8;
  public static final int EOF = 0;
  public static final int tfin = 10;
  public static final int error = 1;
  public static final int tdiv = 5;
  public static final int tchar = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tnum",
  "trest",
  "tsum",
  "tdiv",
  "tmul",
  "tpot",
  "tmod",
  "tinicio",
  "tfin",
  "tcadena",
  "tbool",
  "tchar"
  };
}

