/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Analizadores.Parser;
import Analizadores.Scanner;
import Instrucciones.Instruction;
import AST.Python;
import AST.TablaError;
import java.awt.Desktop;
import AST.DiagramaFlujo;

/**
 *
 * @author TheJhonX
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    
    NumeroLinea numLinea;
    
    public Interface() {
        initComponents();
        numLinea = new NumeroLinea(jCajaTexto);
        jScrollPane1.setRowHeaderView(numLinea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jCajaTexto = new javax.swing.JTextArea();
        jBtnClean = new javax.swing.JButton();
        jBtnRun = new javax.swing.JButton();
        jButtonPython = new javax.swing.JButton();
        jButtonGo = new javax.swing.JButton();
        jshowErrores = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jOpenFile = new javax.swing.JMenuItem();
        JSaveAs = new javax.swing.JMenuItem();
        jReport = new javax.swing.JMenu();
        jFlowchart = new javax.swing.JMenuItem();
        jErrors = new javax.swing.JMenuItem();
        jView = new javax.swing.JMenu();
        jUserManual = new javax.swing.JMenuItem();
        jTechManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 1 OLC");

        jCajaTexto.setColumns(20);
        jCajaTexto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCajaTexto.setRows(5);
        jCajaTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jCajaTexto);

        jBtnClean.setText("Clean");
        jBtnClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnCleanMousePressed(evt);
            }
        });

        jBtnRun.setText("Run");
        jBtnRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnRunMousePressed(evt);
            }
        });

        jButtonPython.setText("Codigo en Python");
        jButtonPython.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonPythonMousePressed(evt);
            }
        });

        jButtonGo.setText("Codigo en Golang");

        jshowErrores.setText("0 errores");

        jFile.setText("File");
        jFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFileMousePressed(evt);
            }
        });

        jOpenFile.setText("Open file");
        jOpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOpenFileMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jOpenFileMousePressed(evt);
            }
        });
        jOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenFileActionPerformed(evt);
            }
        });
        jFile.add(jOpenFile);

        JSaveAs.setText("Save as");
        JSaveAs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JSaveAsMousePressed(evt);
            }
        });
        jFile.add(JSaveAs);

        jMenuBar1.add(jFile);

        jReport.setText("Report");

        jFlowchart.setText("Flowchart");
        jFlowchart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFlowchartMousePressed(evt);
            }
        });
        jReport.add(jFlowchart);

        jErrors.setText("Errors");
        jErrors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jErrorsMousePressed(evt);
            }
        });
        jErrors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jErrorsActionPerformed(evt);
            }
        });
        jReport.add(jErrors);

        jMenuBar1.add(jReport);

        jView.setText("View");

        jUserManual.setText("User manual");
        jUserManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jUserManualMousePressed(evt);
            }
        });
        jView.add(jUserManual);

        jTechManual.setText("Technical manual");
        jTechManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTechManualMousePressed(evt);
            }
        });
        jView.add(jTechManual);

        jMenuBar1.add(jView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnClean)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnRun))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jshowErrores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPython)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonGo)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnClean)
                    .addComponent(jBtnRun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPython, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jshowErrores))
                    .addComponent(jButtonGo))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOpenFileActionPerformed
    
    
    private void jOpenFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOpenFileMouseClicked

    }//GEN-LAST:event_jOpenFileMouseClicked

    private void jFileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFileMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileMousePressed
    
    
    String ruta_archivo = "";
    
    private String readFile(File _file){
        String text = "";
        try{
            BufferedReader br = new BufferedReader(new FileReader(_file));
            String aux;
            while((aux = br.readLine())!=null)
            {
                text += aux + "\n";
            }
            br.close();
        }catch(IOException e){
            System.out.println(e.getMessage());
        }
        
        return text;
    }
    
    private void saveFile(File _file, String text){
        FileWriter write;
        try {

            write = new FileWriter(_file, true);
            write.write(text);
            write.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar, ponga nombre al archivo");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar, en la salida");
        }
    }
    
    
    /*Al hacer click sobre el submenu Open file*/
    private void jOpenFileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOpenFileMousePressed
        JFileChooser chooser=new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.olc", "olc");
        chooser.setFileFilter(filtro);
        int selec = chooser.showOpenDialog(null);
        if (selec == JFileChooser.APPROVE_OPTION){
            //ruta_archivo = chooser.getSelectedFile().getPath();
            this.setTitle(chooser.getSelectedFile().getName());
            String texto = readFile(chooser.getSelectedFile());
            //System.out.println(texto);
            jCajaTexto.setText(texto);
        }
    }//GEN-LAST:event_jOpenFileMousePressed
    
    /*Al hacer click sobre el submenu Save as*/
    private void JSaveAsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSaveAsMousePressed
        JFileChooser save = new JFileChooser();
        /*Comprobar al guardar no lo guarda con la extension definida*/
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.olc", "olc");
        save.setFileFilter(filtro);
        int selec = save.showSaveDialog(null);
        if (selec == JFileChooser.APPROVE_OPTION){
            save.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            saveFile(save.getSelectedFile(), jCajaTexto.getText());
        }
    }//GEN-LAST:event_JSaveAsMousePressed

    private void jBtnRunMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRunMousePressed
        try {
            String text = jCajaTexto.getText();
            Instruction instr = Instruction.getInstance();
            instr.analize(text);
            for (int i=0; i<instr.list.size(); i++){
                System.out.println(instr.list.get(i).getMessage() + " Linea " + instr.list.get(i).getLine());
            }
            jshowErrores.setText(instr.list.size() + " errores");
            System.out.println("--------------------------------");
            instr.createASTGraph(instr.ast);
            System.out.println("AST creado");
            System.out.println("--------------------------------");
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBtnRunMousePressed

    private void jErrorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jErrorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jErrorsActionPerformed

    private void jErrorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jErrorsMousePressed
        Instruction instr = Instruction.getInstance();
        TablaError t = new TablaError();
        t.createHtmlFile(instr.list);
        System.out.println("Tabla.html creado");
        System.out.println("--------------------------------");
    }//GEN-LAST:event_jErrorsMousePressed

    private void jButtonPythonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPythonMousePressed
        try{
            Modal m = new Modal(this, true);
            m.setVisible(true);
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
        //p.createPyFile(codePy);
        
        System.out.println("Archivo.py creado");
        System.out.println("--------------------------------");
    }//GEN-LAST:event_jButtonPythonMousePressed

    private void jBtnCleanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCleanMousePressed
        jCajaTexto.setText("");
    }//GEN-LAST:event_jBtnCleanMousePressed

    private void jUserManualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserManualMousePressed
        try{
            File file = new File("src\\Manuales\\Manual de usuario.pdf");
            if (file.exists()){
                Desktop.getDesktop().open(file);
            }
        }catch (IOException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jUserManualMousePressed

    private void jTechManualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTechManualMousePressed
        try{
            File file = new File("src\\Manuales\\Manual Tecnico.pdf");
            if (file.exists()){
                Desktop.getDesktop().open(file);
            }
        }catch (IOException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jTechManualMousePressed

    private void jFlowchartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFlowchartMousePressed
        Instruction instr = Instruction.getInstance();
        DiagramaFlujo d = new DiagramaFlujo();
        d.createASTGraph(instr.ast);
        System.out.println("diagrama creado");
        System.out.println("--------------------------------");
    }//GEN-LAST:event_jFlowchartMousePressed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JSaveAs;
    private javax.swing.JButton jBtnClean;
    private javax.swing.JButton jBtnRun;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonPython;
    private javax.swing.JTextArea jCajaTexto;
    private javax.swing.JMenuItem jErrors;
    private javax.swing.JMenu jFile;
    private javax.swing.JMenuItem jFlowchart;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jOpenFile;
    private javax.swing.JMenu jReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jTechManual;
    private javax.swing.JMenuItem jUserManual;
    private javax.swing.JMenu jView;
    private javax.swing.JLabel jshowErrores;
    // End of variables declaration//GEN-END:variables
}
